bot:
    # Bot token
    token: "<add-token-here>"
    # Command prefix
    prefix: +
    log-channel: 000000000000000000
    ticket-category: 000000000000000000

database:
    # Address and port of the mysql server
    address: "127.0.0.1"
    port: 3306
    # Name of the database to use
    name: "supportbot"
    # Username and password for authentication
    user: ""
    password: ""