bot:
    # Bot token
    token: "<add-token-here>"
    # Command prefix
    prefix: "+"
    # Channel where ticket logs are posted
    log-channel: 000000000000000000
    # Category where the ticket will be created, it will have the same permissions of that ticket plus read permissions for the user opening the ticket
    ticket-category: 000000000000000000
    # Message posted when a ticket is opened
    welcome-message: "Please describe your issue below, and include all information needed for us to take action, such as coordinates, in-game names and screenshots/chat logs."
    # Decides what messages are shown in console, possible values are: Critical, Error, Warning, Info, Debug
    console-log-level: "Info"

transcripts:
    timestamp-format: "yyyy-MM-dd HH:mm"

database:
    # Address and port of the mysql server
    address: "127.0.0.1"
    port: 3306
    # Name of the database to use
    name: "supportbot"
    # Username and password for authentication
    user: ""
    password: ""

permissions:
    # ID of the role allowed to use admin and moderator commands
    admin-role: 000000000000000000
    # ID of the role allowed to use moderator commands
    moderator-role: 000000000000000000